[package]
name = "esm-parser"
version = "0.2.0"
authors = ["tRuTrIx <trutrix@monocyte.host>", "StealthOfKing <sok@monocyte.host>"]
edition = "2021"
description = "ESM file parser"

[dependencies]
chunk-parser = { git = "https://github.com/StealthOfKing/rust-chunk-parser.git" }
esm-bindings = { git = "https://github.com/trutrix/esm-bindings.git" }

[patch."https://github.com/StealthOfKing/rust-chunk-parser-derive.git"]
chunk-parser-derive = { path = "../chunk-parser-derive" }

[patch."https://github.com/StealthOfKing/rust-chunk-parser.git"]
chunk-parser = { path = "../chunk-parser" }

[patch."https://github.com/trutrix/esm-bindings.git"]
esm-bindings = { path = "../esm-bindings" }
